### ISSUE TITLE
LAS v6 UI under baker branch throws an error when trying to remove a user defined variable

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#105]
**Reported by @kevin-obrien on 31 Jul 2007 15:06 UTC**
When trying to remove a user defined variable, LAS throws this error:

LAS server error

You have encountered an unexpected User Interface error! Please click here to return to the Datasets page. If this error persists please contact the LAS administrator for this site.

The following error occurred:

javax.servlet.ServletException: Can not issue data manipulation statements with executeQuery().
    at gov.noaa.pmel.tmap.las.luis.FormFilter.doFilter(FormFilter.java:103)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)

The sequence of events that make this happen is:
   o Select Coads climatology
   o Select "Air Temperature"
   o on constraints page, click on define variable link
   o define variable averaged in x and t, then hit next
   o On constraints page, select the "variables" link
   o Click on "remove a user defined variable"
   o Select the "Air Temperature_1" variable, and then hit next

and blammo....

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/101

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 1 Aug 2007 20:56 UTC**
Fixed in r1605.
