### ISSUE TITLE
addXML error when configuring from IOOS thredds catalog

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1115]
**Reported by @kevin-obrien on 28 Sep 2011 21:03 UTC**

I'm running into an addXML error when trying to configure the IOOS catalog.  Here's the command and error:

$ sh bin/addXML.sh -t http://ferret.pmel.noaa.gov/geoide/geoIDECleanCatalogs/2CF2728013B3968CD6B635FAC7631CB7.xml -v

```
Exception in thread "main" java.lang.NullPointerException
        at gov.noaa.pmel.tmap.addxml.addXML.addBeansToDoc(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.createXMLfromTHREDDSCatalog(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.LASConfig(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.main(Unknown Source)

```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1109

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 28 Sep 2011 22:04 UTC**
My bad.  I accidentally checked in some changes prematurely.  This is fixed/reverted in r12807.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 29 Sep 2011 21:23 UTC**
Oops not fixed.  Stand by...

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 7 Oct 2011 16:18 UTC**
Changes from r12850 fix addXML so this catalog runs to completion without a fatal error.
