### ISSUE TITLE
Correlation Viewer plot annotation/info button in wrong view states

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1252]
**Reported by kofi.weusijana on 19 Jun 2012 21:31 UTC**
It looks pressed when annotations are NOt showing and not-pressed when annotations are showing

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1246

**Comment by karlmsmith** [comment]
**Modified by kofi.weusijana on 29 Jun 2012 18:46 UTC**

**Comment by karlmsmith** [comment]
**Comment by kofi.weusijana on 6 Jul 2012 00:05 UTC**
I did not observe the Correlation button being in a wrong state. The button works but the resulting window is broken because of the error below (looks like a JS object that is supposed to be a constructor is resolved as a handler at DrawSingleFeature.java:63). Looking at the documentation (see [https://docs.google.com/a/noaa.gov/document/d/1H0so4fRNwR-KWkR5qmU34nrTCUH0vH2milWrsdeeJag/edit LAS Dev Milestones]), the Correlation feature isn't supposed to be ready until v8.1, so I'm moving it out of the 8.0 Alpha milestone and commented the correlationButton out of the OperationsMenu.java constructor.
https://dunkel.pmel.noaa.gov/trac/las/changeset/14301
--

```
16:13:53.780 [ERROR] [gov.noaa.pmel.tmap.las.Correlation] Failed to create an instance of 'gov.noaa.pmel.tmap.las.client.Correlation' via deferred binding 

com.google.gwt.core.client.JavaScriptException: (TypeError): handler is not a constructor
    at com.google.gwt.dev.shell.BrowserChannelServer.invokeJavascript(BrowserChannelServer.java:248)
    at com.google.gwt.dev.shell.ModuleSpaceOOPHM.doInvoke(ModuleSpaceOOPHM.java:136)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNative(ModuleSpace.java:561)
    at com.google.gwt.dev.shell.ModuleSpace.invokeNativeObject(ModuleSpace.java:269)
    at com.google.gwt.dev.shell.JavaScriptHost.invokeNativeObject(JavaScriptHost.java:91)
    at gov.noaa.pmel.tmap.las.client.openlayers.DrawSingleFeatureImpl.create(DrawSingleFeatureImpl.java)
    at gov.noaa.pmel.tmap.las.client.openlayers.DrawSingleFeature.&lt;init&gt;(DrawSingleFeature.java:63)
    at gov.noaa.pmel.tmap.las.client.map.OLMapWidget.init(OLMapWidget.java:460)
    at gov.noaa.pmel.tmap.las.client.map.OLMapWidget.&lt;init&gt;(OLMapWidget.java:195)
    at gov.noaa.pmel.tmap.las.client.Correlation.&lt;init&gt;(Correlation.java:101)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at com.google.gwt.dev.shell.ModuleSpace.rebindAndCreate(ModuleSpace.java:465)
    at com.google.gwt.dev.shell.ModuleSpace.onLoad(ModuleSpace.java:375)
    at com.google.gwt.dev.shell.OophmSessionHandler.loadModule(OophmSessionHandler.java:200)
    at com.google.gwt.dev.shell.BrowserChannelServer.processConnection(BrowserChannelServer.java:525)
    at com.google.gwt.dev.shell.BrowserChannelServer.run(BrowserChannelServer.java:363)
    at java.lang.Thread.run(Thread.java:722)
```

**Comment by karlmsmith** [comment]
**Comment by kofi.weusijana on 6 Jul 2012 18:12 UTC**
Moved back to 8.0 Beta to cover the property-property plot functionality.

**Comment by karlmsmith** [comment]
**Modified by kofi.weusijana on 10 Jul 2012 23:20 UTC**

**Comment by karlmsmith** [comment]
**Comment by kofi.weusijana on 11 Jul 2012 00:11 UTC**
https://dunkel.pmel.noaa.gov/trac/las/changeset/14356

**Comment by karlmsmith** [comment]
**Modified by kofi.weusijana on 9 Oct 2012 22:12 UTC**
