### ISSUE TITLE
One Panel, One Variable, Analysis doesn't work in IE

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1274]
**Reported by kofi.weusijana on 9 Jul 2012 18:20 UTC**
* Open in IE:
http://dunkel.pmel.noaa.gov:8920/v8/UI.vm#panelHeaderHidden=false;differences=false;autoContour=false;globalMin=-40.76;globalMax=30;xDSID=coads_climatology_cdf;varid=airt;imageSize=auto;over=xy;compute=Averagetoken;dsid=coads_climatology_cdf;varid=airt;xlo=200;xhi=200;ylo=0;yhi=0;xlo=160.3125;xhi=215.15625;ylo=11.25;yhi=49.21875;tlo=15-Jan;thi=15-Dec;operation_id=Plot_1D;view=t
* No image shows and the Display Image button is disabled.
* If you are using a server that has the logger on you will see errors:
http://dunkel.pmel.noaa.gov:8888/baker/UI.vm#panelHeaderHidden=false;differences=false;autoContour=false;globalMin=-40.76;globalMax=30;xDSID=coads_climatology_cdf;varid=airt;imageSize=auto;over=xy;compute=Averagetoken;dsid=coads_climatology_cdf;varid=airt;xlo=200;xhi=200;ylo=0;yhi=0;xlo=160.3125;xhi=215.15625;ylo=11.25;yhi=49.21875;tlo=15-Jan;thi=15-Dec;operation_id=Plot_1D;view=t
```
Mon Jul 09 10:52:08 GMT-700 2012 com.google.gwt.logging.client.LogConfiguration SEVERE: One or more exceptions caught, see full set in UmbrellaException#getCauses
com.google.gwt.event.shared.UmbrellaException: One or more exceptions caught, see full set in UmbrellaException#getCauses
at Unknown.Ge(StackTraceCreator.java:168)
at Unknown.xd(StackTraceCreator.java:421)
at Unknown.Ed(RuntimeException.java:33)
at Unknown.Jm(UmbrellaException.java:37)
at Unknown.Lm(UmbrellaException.java:26)
at Unknown.Wl(UmbrellaException.java:56)
at Unknown.f8(UI.java:1561)
at Unknown.pab(UI.java:595)
at Unknown.tab(UI.java:579)
at Unknown.HR(RequestCallbackAdapter.java:232)
at Unknown.Pm(Request.java:287)
at Unknown.rn(RequestBuilder.java:395)
at Unknown.anonymous(XMLHttpRequest.java:287)
at Unknown.ae(Impl.java:168)
at Unknown.de(Impl.java:213)
at Unknown.anonymous(Impl.java:57)
Caused by: com.google.gwt.xml.client.impl.DOMNodeException: Error during DOM manipulation of: <analysis/>
at Unknown.Ge(StackTraceCreator.java:168)
at Unknown.Bd(StackTraceCreator.java:421)
at Unknown.Dd(RuntimeException.java:29)
at Unknown.w4(DOMException.java:36)
at Unknown.g5(DOMNodeException.java:36)
at Unknown.w5(ElementImpl.java:96)
at Unknown.mhb(AnalysisSerializable.java:13)
at Unknown.Gjb(OutputPanel.java:609)
at Unknown.h8(UI.java:904)
at Unknown.H9(WidgetSelectionChangeEvent.java:49)
at Unknown.Ycb(WidgetSelectionChangeEvent.java:32)
at Unknown.km(GwtEvent.java:76)
at Unknown.Wl(EventBus.java:67)
at Unknown.f8(UI.java:1561)
at Unknown.pab(UI.java:595)
at Unknown.tab(UI.java:579)
at Unknown.HR(RequestCallbackAdapter.java:232)
at Unknown.Pm(Request.java:287)
at Unknown.rn(RequestBuilder.java:395)
at Unknown.anonymous(XMLHttpRequest.java:287)
at Unknown.ae(Impl.java:168)
at Unknown.de(Impl.java:213)
at Unknown.anonymous(Impl.java:57)
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError): Type mismatch
at Unknown.Ge(StackTraceCreator.java:168)
at Unknown.Gd(StackTraceCreator.java:421)
at Unknown.BF(Exceptions.java:29)
at Unknown._5(XMLParserImpl.java:242)
at Unknown.w5(ElementImpl.java:95)
at Unknown.mhb(AnalysisSerializable.java:13)
at Unknown.Gjb(OutputPanel.java:609)
at Unknown.h8(UI.java:904)
at Unknown.H9(WidgetSelectionChangeEvent.java:49)
at Unknown.Ycb(WidgetSelectionChangeEvent.java:32)
at Unknown.km(GwtEvent.java:76)
at Unknown.Wl(EventBus.java:67)
at Unknown.f8(UI.java:1561)
at Unknown.pab(UI.java:595)
at Unknown.tab(UI.java:579)
at Unknown.HR(RequestCallbackAdapter.java:232)
at Unknown.Pm(Request.java:287)
at Unknown.rn(RequestBuilder.java:395)
at Unknown.anonymous(XMLHttpRequest.java:287)
at Unknown.ae(Impl.java:168)
at Unknown.de(Impl.java:213)
at Unknown.anonymous(Impl.java:57)
```

Subversion Info:

Path: .
URL: svn+ssh://dunkel.pmel.noaa.gov/home/users/tmap/svn/repos/baker/branches/v8-UI
Repository Root: svn+ssh://dunkel.pmel.noaa.gov/home/users/tmap/svn/repos
Repository UUID: fdbf22ae-c210-0410-be80-ca943da6b8f8
Revision: 14312
Node Kind: directory
Schedule: normal
Last Changed Author: rhs
Last Changed Rev: 14312 
Last Changed Date: 2012-07-08 17:05:20 -0700 (Sun, 08 Jul 2012)

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1268

**Comment by karlmsmith** [comment]
**Comment by kofi.weusijana on 9 Jul 2012 21:45 UTC**
Fixed by avoiding IE evaluating a null when it expects a String object.
https://dunkel.pmel.noaa.gov/trac/las/changeset/14323
