### ISSUE TITLE
Plot images fail to render when comparing Hofmuller Plots

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1355]
**Reported by kofi.weusijana on 15 Aug 2012 20:43 UTC**
Found in r14708:
* Choose under Hofmuller Plots "Longitude-time"
* Choose "Compare 2" or "Compare 4"
 * Only the main plot is rendered and if logging is on you will see the following error stack trace (thrown from DateTimeWidget.java:496):
```
Caused by: com.google.gwt.core.client.JavaScriptException: (TypeError): Unable to get value of the property 'org_gwttime_time_base_BaseDateTime_iChronology': object is null or undefined
   at Unknown.com_google_gwt_core_client_impl_StackTraceCreator$CollectorEmulated_$fillInStackTrace__Lcom_google_gwt_core_client_impl_StackTraceCreator$CollectorEmulated_2Ljava_lang_Throwable_2V(StackTraceCreator.java:168)
   at Unknown.com_google_gwt_core_client_JavaScriptException_JavaScriptException__Ljava_lang_Object_2V(StackTraceCreator.java:421)
   at Unknown.com_google_gwt_lang_Exceptions_caught__Ljava_lang_Object_2Ljava_lang_Object_2(Exceptions.java:29)
   at Unknown.org_gwttime_time_base_AbstractDateTime_$getDayOfMonth__Lorg_gwttime_time_base_AbstractDateTime_2I(AbstractDateTime.java:161)
   at Unknown.gov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_$getFerretDateLo__Lgov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_2Ljava_lang_String_2(DateTimeWidget.java:496)
   at Unknown.gov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_$checkRangeEndYear__Lgov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_2V(DateTimeWidget.java:779)
   at Unknown.gov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_$setRange__Lgov_noaa_pmel_tmap_las_client_laswidget_DateTimeWidget_2ZV(DateTimeWidget.java:380)
   at Unknown.gov_noaa_pmel_tmap_las_client_laswidget_AxesWidgetGroup_$setRange__Lgov_noaa_pmel_tmap_las_client_laswidget_AxesWidgetGroup_2Ljava_lang_String_2ZV(AxesWidgetGroup.java:142)
   at Unknown.gov_noaa_pmel_tmap_las_client_laswidget_OutputPanel_$setRanges__Lgov_noaa_pmel_tmap_las_client_laswidget_OutputPanel_2Ljava_lang_String_2Ljava_util_List_2V(OutputPanel.java:2585)
   at Unknown.gov_noaa_pmel_tmap_las_client_UI_$turnOffAnalysis__Lgov_noaa_pmel_tmap_las_client_UI_2V(UI.java:1995)
   at Unknown.gov_noaa_pmel_tmap_las_client_UI_$compareMenuChanged__Lgov_noaa_pmel_tmap_las_client_UI_2V(UI.java:981)
   at Unknown.gov_noaa_pmel_tmap_las_client_UI$29_onChange__Lcom_google_gwt_event_dom_client_ChangeEvent_2V(UI.java:1334)

```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1349

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 16 Aug 2012 14:37 UTC**
Fixed in r14714.  Fixes problem introduced when setting ranges for ortho axes when grid is scattered.
