### ISSUE TITLE
Cross over check throws java exception

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1606]
**Reported by @kevin-obrien on 29 Jul 2014 22:49 UTC**

Running the crossever check from the vessel name "mooring" on this link:

```
http://dunkel.pmel.noaa.gov:8680/socat/getTrajectoryTable.do?catid=socatV3_c6c1_d431_8194&xml=%3C%3Fxml+version%3D%221.0%22%3F%3E%3ClasRequest+href%3D%22file%3Alas.xml%22%3E%3Cargs%3E%3Clink+match%3D%22%2Flasdata%2Fdatasets%2FsocatV3_c6c1_d431_8194%2Fvariables%2FfCO2_recommended-socatV3_c6c1_d431_8194%22+%2F%3E%3Cregion%3E%3Crange+type%3D%22x%22+low%3D%22-79.189279609121%22+high%3D%22-52.24357267101%22+%2F%3E%3Crange+type%3D%22y%22+low%3D%2228.946088104089%22+high%3D%2244.590448698885%22+%2F%3E%3Crange+type%3D%22t%22+low%3D%2212-Aug-2012+00%3A00%22+high%3D%2201-Mar-2014+00%3A00%22+%2F%3E%3C%2Fregion%3E%3Cconstraint+type%3D%22variable%22+id%3D%22socatV3_c6c1_d431_8194_fCO2_recommended-socatV3_c6c1_d431_8194%22+op%3D%22ne%22%3E%3Clink+match%3D%22%2Flasdata%2Fdatasets%2FsocatV3_c6c1_d431_8194%2Fvariables%2FfCO2_recommended-socatV3_c6c1_d431_8194%22+%2F%3E%3Cv%3ENaN%3C%2Fv%3E%3C%2Fconstraint%3E%3C%2Fargs%3E%3Clink+match%3D%22%2Flasdata%2Foperations%2Foperation[%40ID%3D%27TrajectoryTable%27]%22+%2F%3E%3Cproperties%3E%3Cferret%3E%3Cview%3Exyt%3C%2Fview%3E%3Csize%3E.8333%3C%2Fsize%3E%3Cimage_format%3Egif%3C%2Fimage_format%3E%3Cannotations%3Efile%3C%2Fannotations%3E%3C%2Fferret%3E%3Clas%3E%3Coutput_type%3Ehtml%3C%2Foutput_type%3E%3Cdebug%3Efalse%3C%2Fdebug%3E%3C%2Flas%3E%3Cproduct_server%3E%3Cversion%3E7.3%3C%2Fversion%3E%3C%2Fproduct_server%3E%3C%2Fproperties%3E%3C%2FlasRequest%3E
```

 causes a java exception to get thrown in the catalina.out file.

Here's the error:

```
Jul 29, 2014 1:31:51 PM org.apache.struts.chain.commands.AbstractExceptionHandler execute
WARNING: Unhandled exception
org.apache.struts.chain.commands.InvalidPathException: No action config found for the specified url.
        at org.apache.struts.chain.commands.AbstractSelectAction.execute(AbstractSelectAction.java:71)
        at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
        at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:304)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
        at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at gov.noaa.pmel.tmap.las.filter.RequestInputFilter.doFilter(RequestInputFilter.java:240)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:472)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:99)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:936)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:407)
        at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1004)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:589)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1110)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:603)
        at java.lang.Thread.run(Thread.java:722)

```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1599

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 30 Jul 2014 21:38 UTC**
This is fixed in r18051.

In struts-config.xml the configuration for the crossovers should look like this:

<action path="/getCrossovers" type="gov.noaa.pmel.tmap.las.ui.GetCrossovers"/>

with a lower case "O".
