### ISSUE TITLE
xtra.pmel.noaa.gov:8580:11012 exception showing up in the logs

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1671]
**Reported by @karlmsmith on 4 Sep 2014 03:38 UTC**
Looking through the localhost.2014-09-03.log on Xtra to see what might be failing with logging in through access.pmel.noaa.gov/socat (which uses port 11012 to let the outside world in) I see the following:
```
http://xtra.pmel.noaa.gov:8580:11012/SocatQCEditor/JavaScript/components/gov.noaa.pmel.tmap.las.UI/
java.net.MalformedURLException: For input string: "8580:11012"
	at java.net.URL.<init>(URL.java:619)
	at java.net.URL.<init>(URL.java:482)
	at java.net.URL.<init>(URL.java:431)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.loadSerializationPolicy(RemoteServiceServlet.java:55)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.doGetSerializationPolicy(RemoteServiceServlet.java:293)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.getSerializationPolicy(RemoteServiceServlet.java:157)
	at com.google.gwt.user.server.rpc.impl.ServerSerializationStreamReader.prepareToRead(ServerSerializationStreamReader.java:491)
	at com.google.gwt.user.server.rpc.RPC.decodeRequest(RPC.java:240)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:206)
	at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
	at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NumberFormatException: For input string: "8580:11012"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:492)
	at java.lang.Integer.parseInt(Integer.java:527)
	at java.net.URLStreamHandler.parseURL(URLStreamHandler.java:217)
	at java.net.URL.<init>(URL.java:614)
	... 32 more
```
Is this a result of answering "no" to the proxy?  Although this is a strange mix with their 11012 directly to our 8580 (I think) so I am not sure what to say here.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1664

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 8 Dec 2014 20:27 UTC**
I am also seeing this with the Upload Dashboard, so not something particular to LAS:
```
SEVERE: DashboardListServlet: Malformed moduleBaseURL: http://xtra.pmel.noaa.gov:8580:11012/SocatUploadDashboard/SocatUploadDashboard/
java.net.MalformedURLException: For input string: "8580:11012"
    at java.net.URL.<init>(URL.java:619)
    at java.net.URL.<init>(URL.java:482)
    at java.net.URL.<init>(URL.java:431)
    at com.google.gwt.user.server.rpc.RemoteServiceServlet.loadSerializationPolicy(RemoteServiceServlet.java:58)
 ....
```

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 6 Mar 2015 22:57 UTC**
Issue with access.pmel.noaa.gov proxy.  Changed from a pass-through proxy to a "virtual-machine" seems to have fixed the problem.
