### ISSUE TITLE
SOCAT: server failing after some number of days or uses.

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1696]
**Reported by @karlmsmith on 10 Nov 2014 23:26 UTC**
The SocatQCEditor LAS was failing when I went to access it today.  The error message was a NullPointerException.  When I look in the tomcat logs, at the start of the day I saw this exception:
```
Nov 10, 2014 1:59:57 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [default] in context with path [/SocatQCEditor] threw exception
java.io.FileNotFoundException: /home/xtra/tmap/socat/tomcat-7.0.55/webapps/SocatQCEditor/JavaScript/frameworks/OpenLayers/OpenLayers.js (Too many open files)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at org.apache.naming.resources.FileDirContext$FileResource.streamContent(FileDirContext.java:898)
	at org.apache.catalina.servlets.DefaultServlet.copy(DefaultServlet.java:2015)
	at org.apache.catalina.servlets.DefaultServlet.serveResource(DefaultServlet.java:992)
	at org.apache.catalina.servlets.DefaultServlet.doGet(DefaultServlet.java:442)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
	at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)
```
There were similar exceptions (too many open files) for some of the other webapps as well.  Since I do not remember ever seeing this before, and supposedly the SocatQCEditor is the main thing getting used repeatedly, I am suspicious that it is the latest SOCAT/LAS leaving some resource open.

Checking the localhost.2014-11-*.log files, the first appearance was Nov 8 with:
```
Nov 08, 2014 7:38:07 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [action] in context with path [/SocatQCEditor] threw exception [java.net.SocketException: Too many open files] with root cause
java.net.SocketException: Too many open files
    at java.net.Socket.createImpl(Socket.java:447)
    at java.net.Socket.<init>(Socket.java:421)
    at java.net.Socket.<init>(Socket.java:280)
    at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:80)
    at org.apache.commons.httpclient.protocol.DefaultProtocolSocketFactory.createSocket(DefaultProtocolSocketFactory.java:122)
    at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
    at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387)
    at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
    at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)
    at gov.noaa.pmel.tmap.las.proxy.LASProxy.executeGetMethodAndReturnStream(LASProxy.java:113)
    at gov.noaa.pmel.tmap.las.ui.GetTrajectoryTable.execute(GetTrajectoryTable.java:401)
    at org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:58)
    at org.apache.struts.chain.commands.AbstractExecuteAction.execute(AbstractExecuteAction.java:67)
    at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
    at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
    at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:304)
    at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
    at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
    at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
    at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:620)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at gov.noaa.pmel.tmap.las.filter.AddUsernameFilter.doFilter(AddUsernameFilter.java:54)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at gov.noaa.pmel.tmap.las.filter.RequestInputFilter.doFilter(RequestInputFilter.java:240)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:610)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1070)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:611)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:314)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
    at java.lang.Thread.run(Thread.java:745)
```

Interestingly, there is a similar one on Oct 08 as well.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1689

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 11 Nov 2014 15:23 UTC**
/usr/sbin/lsof should tell us something about the accumulating open files. It could be open mysql connections which take up an inode. The place to start is to see if we can identify a pattern to the files being left open so we know where to look.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 12 Nov 2014 16:31 UTC**
I very much suspect that these are open HTTP connections from the creation of table of cruises or the table in the flag editor. There are a ton of connections made and I tried to be careful, but I may have missed closing some.

I will look at the code, but in the meantime output from lsof might be a big help.  Particularly looking at the output before and after opening a table of cruises and before and after opening the flag editor.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 12 Nov 2014 16:54 UTC**
Tests on dunkel confirm that the table of cruises is leaving a ton of open TCP connections:

java      28704       rhs  255u     IPv6            7411502      0t0        TCP dunkel.pmel.noaa.gov:40012->dunkel.pmel.noaa.gov:8660 (CLOSE_WAIT)

I'll keep looking, but I don't immediately see what's not being closed.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 12 Nov 2014 17:51 UTC**
Fixed. The answer is here:

http://www.nuxeo.com/blog/using-httpclient-properly-avoid-closewait-tcp-connections/

I used the method.setRequestHeader("Connection", "close"); since I use a new connection each time.

r18727 in the socat branch and r18728 in the trunk.
