### ISSUE TITLE
SOCAT: unable to assign a large number of WOCE flags

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1698]
**Reported by @karlmsmith on 4 Dec 2014 18:56 UTC**
Judith Hauck reported that she was unable to WOCE out a large number of data points:
``` WOCE out the data for Polarstern 06AQ20090109 between Jan 27 and Mar 06 ```
The WOCE of this large number of data points is valid (instead of a suspend) because the data is during an iron fertilization experiment, so it does not indicate a instrument failure, just an environmental anomaly where this otherwise-valid data should not be added to SOCAT.

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1691

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 8 Dec 2014 20:40 UTC**
Seeing the following Exception in socat/tomcat/logs/localhost.2014-11-17.log on xtra:
```
Nov 27, 2014 4:21:17 AM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [action] in context with path [/SocatQCEditor] threw exception [ClientAbortException:
java.net.SocketException: Broken pipe 
    at java.net.SocketOutputStream.socketWrite0(Native Method)
    at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:113)
    at java.net.SocketOutputStream.write(SocketOutputStream.java:159)
    at org.apache.coyote.http11.InternalOutputBuffer.realWriteBytes(InternalOutputBuffer.java:215)
    at org.apache.tomcat.util.buf.ByteChunk.flushBuffer(ByteChunk.java:480)
    at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:366)
    at org.apache.coyote.http11.InternalOutputBuffer$OutputStreamOutputBuffer.doWrite(InternalOutputBuffer.java:240)
    at org.apache.coyote.http11.filters.ChunkedOutputFilter.doWrite(ChunkedOutputFilter.java:119)
    at org.apache.coyote.http11.AbstractOutputBuffer.doWrite(AbstractOutputBuffer.java:192)
    at org.apache.coyote.Response.doWrite(Response.java:499)
    at org.apache.catalina.connector.OutputBuffer.realWriteBytes(OutputBuffer.java:402)
    at org.apache.tomcat.util.buf.ByteChunk.append(ByteChunk.java:342)
    at org.apache.catalina.connector.OutputBuffer.writeBytes(OutputBuffer.java:432)
    at org.apache.catalina.connector.OutputBuffer.write(OutputBuffer.java:420)
    at org.apache.catalina.connector.CoyoteOutputStream.write(CoyoteOutputStream.java:91)
    at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
    at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
    at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
    at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
    at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
    at java.io.BufferedWriter.write(BufferedWriter.java:230)
    at java.io.Writer.write(Writer.java:157)
    at gov.noaa.pmel.tmap.las.ui.GetTrajectoryTable.execute(GetTrajectoryTable.java:575)
    at org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:58)
....
```

Looks like it might be crash Exception, but not sure.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 8 Dec 2014 22:38 UTC**
Trying this on dunkel, I am able to get the table of values to show after quite awhile (started it, went off to lunch, and the values were up when I got back).  I gave up on waiting (after 30 min) to set all the values to a WOCE flag of 4.  This is all data points between Jan 26 and Mar 6 (inclusive) of 06AQ20090109, and is over 26,100 points.  So if it works or crashes, this is just a very extreme case that should not be expected to work.

Leaving this open for now to remind me to WOCE these points out.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 13 Dec 2014 00:25 UTC**
No changes made to fix WOCE-ing a huge number of data points.  However, the data points in question have now been given a WOCE-4, so closing out this ticket.
