### ISSUE TITLE
SOCAT: crossover check never responds back with the result for some cruises

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#1706]
**Reported by @karlmsmith on 26 Feb 2015 19:49 UTC**
Sumiko Harasawa reported that the crossover check for the following cruises never returns a response (stuck on checking...): 49FA20111004 and 49P120111130
I am able to reproduce this and also notice it happening for 49P120111130.
I see the java process using CPU for awhile after initiating the check.  Compared with successful checks (such as 49P120111005), it appears to complete in about the same amount of time, but a response is never returned to the user.

In the tomcat logs I see an exception traceback:
```
Feb 26, 2015 11:27:37 AM org.apache.struts.chain.commands.ExceptionCatcher postprocess
WARNING: Exception from exceptionCommand 'servlet-exception'
java.lang.UnsupportedOperationException: JsonNull
	at com.google.gson.JsonElement.getAsString(JsonElement.java:191)
	at gov.noaa.pmel.tmap.las.ui.GetCrossovers.checkCrossover(GetCrossovers.java:372)
	at gov.noaa.pmel.tmap.las.ui.GetCrossovers.execute(GetCrossovers.java:236)
   .
   .
   .
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/1699

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 26 Feb 2015 21:37 UTC**
The line of code that is generating a null pointer exception is marked with "==>"
```
                String crossingDate = crossingRow.get(1).getAsString();
                if ( j == 0 ) {
                    cruiseMinDate = crossingDate;
                    JsonArray maxRow = (JsonArray) crossingRows.get(crossingRows.size() -1);
 ==>                cruiseMaxDate = maxRow.get(1).getAsString();
                }
```
But looking at the data, the final dates of the cruises appear valid (assuming that is maxRow).

Hopefully the problem becomes more obvious in a debugger.  But I am not setup for debugging LAS, so hoping Roland can easily check what is going on here.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 2 Mar 2015 22:44 UTC**
Taking back the ticket - problem is a null time value.

From Roland:
I checked in a change on the trunk and the socat branch that will prevent the crossover check from throwing an exception and failing to return information the UI when faced with null time values in that part of the check.  For the cruise I used to debug the problem (642B20111123) there is at least one missing value (null) in the time column of the decimated data set. I wouldn't have thought there should be any null dates in either data set.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 4 Mar 2015 00:52 UTC**
Interestingly, the fix took care of the cruises that were mentioned by Sumiko - they report "none" for the crossovers.

However, I do see that the first six "time" values in the DSG file for 642B20111123 are missing.  (The time limits and crossover check result for this cruise indicates an error occurred.)  The times in the text data file, however, appear to be fine (11/23/2011 13:39:52 to 13:45:16 for the first six, then continues on with 11/23/2011 13:46:19, 13:47:21, etc so nothing unusual).

So need to find out what went wrong with the submit of this cruise.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 4 Mar 2015 16:21 UTC**
Replying to [comment:3 karl.smith]:
> Interestingly, the fix took care of the cruises that were mentioned by Sumiko - they report "none" for the crossovers.


They are not exactly "taken care of" in that a cruise with a missing time is rejected as a potential cross. I think the safest thing to do is just reject cruises with missing time and count on sorting out why the times are bad. But in the end such a cruise might actually be a valid cross.


> 
> However, I do see that the first six "time" values in the DSG file for 642B20111123 are missing.  (The time limits and crossover check result for this cruise indicates an error occurred.)  The times in the text data file, however, appear to be fine (11/23/2011 13:39:52 to 13:45:16 for the first six, then continues on with 11/23/2011 13:46:19, 13:47:21, etc so nothing unusual).
> 
> So need to find out what went wrong with the submit of this cruise.

The problem may have been introduced in the decimation step. Or at least I think  was seeing missing values in the decimated data set.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 4 Mar 2015 17:48 UTC**
I see; the problem Sumiko was seeing was not with those cruises but with this other cruise they has a potential crossover with.

Sadly, I was looking at the full-data DSG file for 642B2011113 in the above report of the first six times missing.  I am copying all the current SOCAT data (including DSG files) from xtra to put on dunkel.  I will assess how many of these DSG files have missing times and try to see if these missing times arise from the DSG file generation.  If not, then I will see what the QC history is on them to see if there is a common theme (e.g., some sort of updating).

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 5 Mar 2015 23:06 UTC**
Only three datasets with the missing time values:

642B20111123: first six values of all fields were missing.  Upon resubmit (on flat) there were no longer any missing time values.  Not sure of the cause.  Cruise had been suspended for other data problems.  DSG file replaced with updated one (still suspended).

642B20130504: first six value of all fields were missing.  Upon resubmit (on flat) there were no longer any missing time values.  Not sure of the cause.  Cruise had not been examined (no QC, no WOCE), so DSG file replaced with the updated one.

316419950101: text data file has many data lines without any data except the date.  There had been automatically removed prior to creating the DSG file (hack for Benjamin for v3 only - this hack is being removed).  The missing time value correspond to data lines with data but with an invalid date of Feb 29, 1995, which got turned into a missing value when the DSG file was created.  I suspended the dataset with the comment that the original data needed to be cleaned up; it contained dates of Feb 29, 1995 and contained many lines of data with no actual data except a date and time.

Code changed so an invalid date will raise an exception when generating the DSG file, thus resulting in a error message when attempting to submit the cruise for QC.  Investigating why the SanityChecker error messages (which were generated) did not stop the submitting of the cruise: no column number was associated with the bad time (since it was split over more than one column) and thus the WOCE-4 was not associated with a bad time.  There was a TODO: in the code indicating this is a problem that needed to be fixed; now it is being fixed.

**Comment by karlmsmith** [comment]
**Comment by @karlmsmith on 6 Mar 2015 22:52 UTC**
Generating a DSG file with missing time fails.  

Sanity checker results examined for missing or invalid longitude, latitude, or time, and refuses to submit for QC if these errors are present.  (Hack for Benjamin removed, better checking for invalid times.)

091120090210 was submitted last night with invalid times before I got this update in.  Cruise was suspended and Camilla notified.
