### ISSUE TITLE
Can we support a scalar variable with no geo-referencing in the V6 UI?

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#176]
**Reported by @kevin-obrien on 14 Aug 2007 20:27 UTC**

In running through the first Hudson Bay Scenario from Keith Dixon (see [http://porter.pmel.noaa.gov/trac/las/ticket/170 Ticket 170], I ran into an LAS Server error when trying to define a variable as an xy average of already t-averaged variable.  I have attached a Selenium test file which, when run against [http://porter.pmel.noaa.gov:8780/gfdlBakerRC1/servlets/dataset] should reproduce the error 

The error dump starts out as:

```
LAS server error

You have encountered an unexpected User Interface error! Please click here to return to the Datasets page. If this error persists please contact the LAS administrator for this site.

The following error occurred:

javax.servlet.ServletException
	at gov.noaa.pmel.tmap.las.luis.FormFilter.doFilter(FormFilter.java:103)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at gov.noaa.pmel.tmap.las.luis.SessionFilter.doFilter(SessionFilter.java:506)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at gov.noaa.pmel.tmap.las.luis.ExceptionFilter.doFilter(ExceptionFilter.java:24)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:202)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:173)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:178)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:126)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:105)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:107)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:148)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:869)
	at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:664)
	at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:527)
	at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:80)
	at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:684)
	at java.lang.Thread.run(Thread.java:595)

Root cause of servlet exception was:

javax.servlet.ServletException
	at gov.noaa.pmel.tmap.las.luis.TemplateServlet.error(TemplateServlet.java:123)
	at org.apache.velocity.servlet.VelocityServlet.doRequest(VelocityServlet.java:381)
	at org.apache.velocity.servlet.VelocityServlet.doGet(VelocityServlet.java:317)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:689)
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/172

**Comment by karlmsmith** [comment]
**Attachment from @kevin-obrien on 14 Aug 2007 20:27 UTC**
Selenium file for reproducing bug
REPLACE THIS TEXT WITH UPLOADED FILE /home/merlot/ksmith/git/trac2github/attachments/TRAC_172_GIT_176/GFDLdataPortal_xy_and_t_ave_crash

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 21 Aug 2007 20:07 UTC**
In the old UI you are not allowed to select all of the axes in a data set to be modified when creating a user defined variable.  If you already have t selected then do another step and select x and y you have essentially reduced the data set to a single number which the old UI apparently doesn't allow.

I modified the code so that when doing analysis on analysis variable it checks the previously analized axes in addition to the newly selected axes and sets a warning if all axes are selected (instead of dumping as it does now).

Don't know what this means for the scenario in #170, but don't have a better fix at the moment.

Change set: r1732.

**Comment by karlmsmith** [comment]
**Comment by steven.c.hankin on 22 Aug 2007 18:23 UTC**
When a variable is transfored on all of its axes the result is a scalar.  Such a variable should be accessible through the table and file output products in LAS, even if no meaningful visualizations are possible.  In the case of the GFDL scenario, this single number is the very result that their users are after.  Thus if it is possible to keep the V6 UI from choking, it would be very nice if we could support this.

The conflict, I suppose, is that the variable has no "VIEW" that is normally offered.  In principle it has only a "point" view.  (Though various hacks might be considered to see a point result under some other view.)  A question to ask ourselves is what the cost/benefit might be to support a scalar variable in the V6 UI.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 22 Aug 2007 18:57 UTC**
Will investigate setting the null view to XY to see if we can get the UI to behave.  I suspect that there will be many things that have to be faked to get this to work and will evaluate the cost/benefit when I dig into it.

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 12 Oct 2007 16:13 UTC**
Too much for too little payoff, especially since I think it will be easy to create "data selection" pages compatible with the GFDL custom templates that can be hooked to the v7 "constrain page" (the current UI without the hierarchy of data set selectors).  As long as that UI can handle a scalar variable this will be a better path to this capability.
