### ISSUE TITLE
Product server reports error when processing what appears to be a valid date

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#769]
**Reported by @kevin-obrien on 2 Mar 2010 18:44 UTC**
In the v7.1 las tag, I'm having troubles with the product server not processing what appears to be a valid date.  

The date is coming from addxml, given the command:

sh bin/addXML.sh -n http://thredds1.pfeg.noaa.gov/thredds/dodsC/satellite/MH/chla/5day -a:t

which creates a time axis looking like:

```
  <time-t-id-aed6af95e5 type="t" units="year">
    <arange start="2002-12-29" size="5" step="1" />
  </time-t-id-aed6af95e5>

```

However, that XML causes the below error to be logged and nothing shows up in the v7 UI when the dataset is selected:

```

2010-03-02 10:39:33,441 ERROR [localhost].[/lasV71].[action] - Servlet.service() for servlet action threw exception
java.lang.NumberFormatException: For input string: "2002-12-29"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:1224)
        at java.lang.Double.valueOf(Double.java:475)
        at gov.noaa.pmel.tmap.las.jdom.LASConfig.addTimeAxisAttributes(LASConfig.java:531)
        at gov.noaa.pmel.tmap.las.jdom.LASConfig.getGrid(LASConfig.java:1647)
        at gov.noaa.pmel.tmap.las.jdom.LASConfig.getGrid(LASConfig.java:1671)
        at gov.noaa.pmel.tmap.las.ui.GetGrid.execute(GetGrid.java:81)
        at org.apache.struts.chain.commands.servlet.ExecuteAction.execute(ExecuteAction.java:58)
        at org.apache.struts.chain.commands.AbstractExecuteAction.execute(AbstractExecuteAction.java:67)
        at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
        at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:304)
        at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:190)
        at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
        at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
        at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:690)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:803)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:269)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
        at gov.noaa.pmel.tmap.las.filter.RequestInputFilter.doFilter(RequestInputFilter.java:217)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:215)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:188)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:213)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:174)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:433)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:117)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:108)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:151)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:874)
        at org.apache.coyote.http11.Http11BaseProtocol$Http11ConnectionHandler.processConnection(Http11BaseProtocol.java:665)
        at org.apache.tomcat.util.net.PoolTcpEndpoint.processSocket(PoolTcpEndpoint.java:528)
        at org.apache.tomcat.util.net.LeaderFollowerWorkerThread.runIt(LeaderFollowerWorkerThread.java:81)
        at org.apache.tomcat.util.threads.ThreadPool$ControlRunnable.run(ThreadPool.java:689)
        at java.lang.Thread.run(Thread.java:619)

```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/763

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 2 Mar 2010 21:27 UTC**
Fixed in r4948.
