### ISSUE TITLE
addxml crashes when reading thredds catalog

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#777]
**Reported by @kevin-obrien on 5 Mar 2010 23:40 UTC**

This command crashes addXML:
```
> sh bin/addXML.sh -t http://porter.pmel.noaa.gov:8780/thredds/geoIDECleanCatalogs/C61ABC65BE89E738480778BCCD136ABA.xml -a:t
log4j:WARN No appenders could be found for logger (org.apache.commons.httpclient.params.DefaultHttpParams).
log4j:WARN Please initialize the log4j system properly.
Exception in thread "main" org.jdom.IllegalAddException: Cannot add null object
        at org.jdom.ContentList.add(ContentList.java:125)
        at java.util.AbstractList.add(AbstractList.java:91)
        at org.jdom.Element.addContent(Element.java:811)
        at gov.noaa.pmel.tmap.addxml.addXML.createXMLfromTHREDDSCatalog(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.LASConfig(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.main(Unknown Source)
```

This occurs with both the bakertrunk version of addXML as well as what is checked in on the v71 tag, which i would expect...

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/771

**Comment by karlmsmith** [comment]
**Comment by @noaaroland on 17 Aug 2010 22:11 UTC**
Works as of r5726, though two datasets in this catalog were "file not found" at the remote thredds server at the time I did my test.
