### ISSUE TITLE
addxml fails on HF radar file from NDBC thredds server

### ISSUE THREAD

**Issue by karlmsmith** [NOAA-PMEL/LAS#844]
**Reported by @kevin-obrien on 28 Jun 2010 21:19 UTC**

If I run addxml from the baker trunk (which is addXML v1.6.0, I believe), I'm finding that it fails on an HF radar netcdf file from an NDBC thredds server:

```
> sh bin/addXML.sh -n http://sdf.ndbc.noaa.gov:8080/thredds/dodsC/hfradar_usegc_6km -v
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:222)
        at gov.noaa.pmel.tmap.addxml.addXML.outputXML(Unknown Source)
        at gov.noaa.pmel.tmap.addxml.addXML.main(Unknown Source)
```

Here's what shows up in the addXML.log file:

```
> cat addXML.log 
2010-06-28T14:17:44.503 -0700 [         0][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - Processing netCDF dataset: http://sdf.ndbc.noaa.gov:8080/thredds/dodsC/hfradar_usegc_6km
2010-06-28T14:17:44.901 -0700 [       398][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -          Variable: u
2010-06-28T14:17:44.902 -0700 [       399][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Longitude axis: 
2010-06-28T14:17:44.902 -0700 [       399][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=x units=degrees_east start=-97.8839 step=0.0581 size=701
2010-06-28T14:17:44.903 -0700 [       400][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Latitude axis: 
2010-06-28T14:17:44.903 -0700 [       400][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=y units=degrees_north start=21.736 step=0.0539 size=460
2010-06-28T14:17:44.903 -0700 [       400][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  No vertical axis
2010-06-28T14:17:44.904 -0700 [       401][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Time axis: 
2010-06-28T14:17:45.122 -0700 [       619][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=t units=hour start=2010-06-25 20:00:00 step=1 size=68
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Grid has LatLonProjection.
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -          Variable: v
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Longitude axis: 
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=x units=degrees_east start=-97.8839 step=0.0581 size=701
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Latitude axis: 
2010-06-28T14:17:45.123 -0700 [       620][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=y units=degrees_north start=21.736 step=0.0539 size=460
2010-06-28T14:17:45.124 -0700 [       621][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  No vertical axis
2010-06-28T14:17:45.124 -0700 [       621][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Time axis: 
2010-06-28T14:17:45.125 -0700 [       622][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=t units=hour start=2010-06-25 20:00:00 step=1 size=68
2010-06-28T14:17:45.126 -0700 [       623][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Grid has LatLonProjection.
2010-06-28T14:17:45.126 -0700 [       623][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -          Variable: DOPx
2010-06-28T14:17:45.126 -0700 [       623][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Longitude axis: 
2010-06-28T14:17:45.126 -0700 [       623][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=x units=degrees_east start=-97.8839 step=0.0581 size=701
2010-06-28T14:17:45.127 -0700 [       624][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Latitude axis: 
2010-06-28T14:17:45.127 -0700 [       624][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=y units=degrees_north start=21.736 step=0.0539 size=460
2010-06-28T14:17:45.127 -0700 [       624][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  No vertical axis
2010-06-28T14:17:45.127 -0700 [       624][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Time axis: 
2010-06-28T14:17:45.129 -0700 [       626][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=t units=hour start=2010-06-25 20:00:00 step=1 size=68
2010-06-28T14:17:45.129 -0700 [       626][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Grid has LatLonProjection.
2010-06-28T14:17:45.129 -0700 [       626][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -          Variable: DOPy
2010-06-28T14:17:45.129 -0700 [       626][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Longitude axis: 
2010-06-28T14:17:45.129 -0700 [       626][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=x units=degrees_east start=-97.8839 step=0.0581 size=701
2010-06-28T14:17:45.130 -0700 [       627][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Latitude axis: 
2010-06-28T14:17:45.130 -0700 [       627][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=y units=degrees_north start=21.736 step=0.0539 size=460
2010-06-28T14:17:45.130 -0700 [       627][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  No vertical axis
2010-06-28T14:17:45.130 -0700 [       627][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Time axis: 
2010-06-28T14:17:45.132 -0700 [       629][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML - type=t units=hour start=2010-06-25 20:00:00 step=1 size=68
2010-06-28T14:17:45.132 -0700 [       629][        ] ERROR - gov.noaa.pmel.tmap.addxml.addXML -                  Grid has LatLonProjection.
```

Migrated-From: http://dunkel.pmel.noaa.gov/trac/las/ticket/838

**Comment by karlmsmith** [comment]
**Comment by @kevin-obrien on 28 Jun 2010 21:21 UTC**

I should add that I'm able to open up this dataset using ncdump and Ferret without incident:


```
yes? use "http://sdf.ndbc.noaa.gov:8080/thredds/dodsC/hfradar_usegc_6km"
yes? sh data
     currently SET data sets:
    1> http://sdf.ndbc.noaa.gov:8080/thredds/dodsC/hfradar_usegc_6km  (default)
 name     title                             I         J         K         L
 SITE_LAT Contributing radar site latitud  1:9       ...       ...       ...
 SITE_LON Contributing radar site longitu  1:9       ...       ...       ...
 SITE_CODE
          Contributing radar site code     1:9       ...       ...       ...
 SITE_NETCODE
          Contributing radar site network  1:9       ...       ...       ...
 PROCPARAMS
          RTV processing parameters        1:7       ...       ...       ...
 U                                         1:701     1:460     ...       1:68
 V                                         1:701     1:460     ...       1:68
 DOPX     longitudinal dilution of precis  1:701     1:460     ...       1:68
 DOPY     latitudinal dilution of precisi  1:701     1:460     ...       1:68
 

```

**Comment by karlmsmith** [comment]
**Comment by @kevin-obrien on 28 Jun 2010 21:24 UTC**

Oops.  I'm going to close this ticket because I just realized that I had somehow ended up running my tests from a old addxml build.  If I find errors, i will open another ticket...
